# ind_MA.py
# Exponential Moving Average indicator + descriptor for cl_IndicatorEngine.

import pandas as pd
import pandas_ta_classic as ta


# ---------------------------------------------------------------------------
# Valid price_applied options
# ---------------------------------------------------------------------------
PRICE_APPLIED_OPTIONS = [
    "price_open",
    "price_high",
    "price_low",
    "price_close",
    "price_median",
    "price_typical",
    "price_weighted",
]


def _resolve_price_series(df: pd.DataFrame, price_applied: str) -> pd.Series:
    """Resolves the price_applied field to a pandas Series from a candle DataFrame."""
    if price_applied == "price_open":
        return df["open"]
    elif price_applied == "price_high":
        return df["high"]
    elif price_applied == "price_low":
        return df["low"]
    elif price_applied == "price_close":
        return df["close"]
    elif price_applied == "price_median":
        return (df["high"] + df["low"]) / 2
    elif price_applied == "price_typical":
        return (df["high"] + df["low"] + df["close"]) / 3
    elif price_applied == "price_weighted":
        return (df["open"] + df["high"] + df["low"] + df["close"]) / 4
    else:
        raise ValueError(f"Unknown price_applied value: '{price_applied}'")


def _resolve_price_scalar(brick: pd.Series, price_applied: str) -> float:
    """Resolves the price_applied field to a scalar float from a single candle Series."""
    if price_applied == "price_open":
        return float(brick["open"])
    elif price_applied == "price_high":
        return float(brick["high"])
    elif price_applied == "price_low":
        return float(brick["low"])
    elif price_applied == "price_close":
        return float(brick["close"])
    elif price_applied == "price_median":
        return (float(brick["high"]) + float(brick["low"])) / 2
    elif price_applied == "price_typical":
        return (float(brick["high"]) + float(brick["low"]) + float(brick["close"])) / 3
    elif price_applied == "price_weighted":
        return (float(brick["open"]) + float(brick["high"]) + float(brick["low"]) + float(brick["close"])) / 4
    else:
        raise ValueError(f"Unknown price_applied value: '{price_applied}'")


class cl_MA:
    """
    Exponential Moving Average indicator.
    Calculates EMA over historical candles via pandas_ta_classic and updates
    incrementally (candle-by-candle) using the standard EMA formula.
    """

    def __init__(self, period: int, price_applied: str, color: str) -> None:
        self._period        = period
        self._price_applied = price_applied
        self._color         = color
        self._ema_mult      = 2 / (self._period + 1)
        self._last_ema      = None   # Populated after process_history(); used by process_tick()

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def process_history(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates EMA over the full historical candle DataFrame.

        The indicator always uses the candle chart timestamp column ('time').
        For regular candles this is the real timestamp.
        For Renko candles this is the fake chart timestamp generated by the
        Renko engine. If 'time_real' exists, it is preserved outside the
        indicator and must not be used for chart plotting.

        Parameters
        ----
        df : pd.DataFrame
            Candle history with columns: time, open, high, low, close.

        Returns
        ----
        pd.DataFrame with columns 'time' and 'value', or empty DataFrame
        if the series is too short for the given period.
        """
        price_series = _resolve_price_series(df, self._price_applied)
        ema_series   = ta.ema(price_series, length=self._period)

        if ema_series is None or ema_series.dropna().empty:
            return pd.DataFrame(columns=["time", "value"])

        df_result = pd.DataFrame({
            "time":  df["time"].reset_index(drop=True),
            "value": ema_series.reset_index(drop=True),
        }).dropna(subset=["value"]).reset_index(drop=True)

        # Store the last valid EMA for subsequent incremental updates
        if not df_result.empty:
            self._last_ema = float(df_result.iloc[-1]["value"])

        return df_result

    def process_tick(self, brick: pd.Series) -> pd.Series:
        """
        Incrementally updates the EMA when a new candle/brick is completed.

        The returned 'time' must remain compatible with lightweight-charts.
        Therefore it is returned as pd.Timestamp, never as an int/float. This
        avoids the library interpreting Unix seconds as milliseconds.

        Parameters
        ----
        brick : pd.Series
            Completed candle with fields: time, open, high, low, close.

        Returns
        ----
        pd.Series with fields 'time' and 'value', or None if history has
        not been loaded yet (process_history() was never called).
        """
        if self._last_ema is None:
            return None

        price          = _resolve_price_scalar(brick, self._price_applied)
        new_ema        = price * self._ema_mult + self._last_ema * (1 - self._ema_mult)
        self._last_ema = new_ema

        return pd.Series({
            "time":  brick["time"],
            "value": new_ema,
        })

    # ------------------------------------------------------------------
    # Properties (read-only — used by cl_IndicatorEngine for chart setup)
    # ------------------------------------------------------------------

    @property
    def color(self) -> str:
        return self._color

    @property
    def period(self) -> int:
        return self._period

    @property
    def price_applied(self) -> str:
        return self._price_applied


# ---------------------------------------------------------------------------
# Descriptor — consumed exclusively by cl_IndicatorEngine.
# Encapsulates everything the engine needs to validate and instantiate cl_MA
# without importing or knowing anything about it directly.
# ---------------------------------------------------------------------------

def _validate_MA(cfg: dict) -> tuple[bool, str]:
    """
    Type-specific validation for IND_MA configs.
    Returns (is_valid, reason). Called by cl_IndicatorEngine after generic checks.
    """
    if cfg["period"] <= 0:
        return False, f"'period' must be a positive integer, got {cfg['period']}."
    if cfg["price_applied"] not in PRICE_APPLIED_OPTIONS:
        return False, (
            f"'price_applied' = '{cfg['price_applied']}' is not valid. "
            f"Valid options: {PRICE_APPLIED_OPTIONS}."
        )
    if not cfg["color"].strip():
        return False, "'color' must not be empty."
    return True, ""


def _factory_MA(cfg: dict) -> cl_MA:
    """Instantiates cl_MA from a validated config dict."""
    return cl_MA(
        period        = cfg["period"],
        price_applied = cfg["price_applied"],
        color         = cfg["color"],
    )


def _summary_MA(cfg: dict) -> str:
    """Returns a human-readable summary string for the Logger."""
    return f"period={cfg['period']}, price={cfg['price_applied']}"


# The descriptor is the only object indicators.py imports from this module.
IND_MA_DESCRIPTOR = {
    "type_key":       "IND_MA",
    "required_fields": {
        "ID":            int,
        "name":          str,
        "period":        int,
        "price_applied": str,
        "color":         str,
    },
    "optional_fields": {
        "enabled": True,
    },
    "validate":  _validate_MA,   # callable(cfg) -> (bool, str)
    "factory":   _factory_MA,    # callable(cfg) -> indicator instance
    "summary":   _summary_MA,    # callable(cfg) -> str
}